### ISSUE TITLE
Getting TypeError: can't convert NoneType to int

### ISSUE THREAD

**Issue by codepope** [bwshockley/CircuitPython-i2cEncoderLibV21#2]
Trying out the library for the first time on a Pi Pico with:

Adafruit CircuitPython 6.2.0-beta.3 on 2021-03-04; Raspberry Pi Pico with rp2040

And current bundle. Encoder seems to be recognized but when an INT is triggered, I get

```
Traceback (most recent call last):
  File "code.py", line 94, in <module>
  File "code.py", line 54, in Encoder_INT
  File "i2cencoderlibv21.py", line 227, in update_status
  File "i2cencoderlibv21.py", line 698, in _read_reg
  File "i2cencoderlibv21.py", line 698, in _read_reg
TypeError: can't convert NoneType to int
```

Code is relatively unaltered from the example code in the community bundle save for pin changes and address changes:

```
# Setup the Inturrpt Pin from the encoder.
INT = digitalio.DigitalInOut(board.GP2)
INT.direction = digitalio.Direction.INPUT
INT.pull = digitalio.Pull.UP

# Initialize the device.
i2c = busio.I2C(board.GP1, board.GP0)
encoder = i2cencoderlibv21.I2CEncoderLibV21(i2c, 0x70)
```

**Comment by codepope** [comment]
Have addressed this in a PR #3

**Comment by tschundler** [comment]
Thanks - I'm running into the same issue too. Also just not setting the lengths / offsets works too

**Comment by bwshockley** [comment]
Pulled in PR #3.
